
apiVersion: v1
kind: Pod
metadata:
  name: app-a-pod1
  labels:
    app: app-a
spec:
  containers:
    - name: app-a-main
      image: node:18
      ports:
        - containerPort: 3000
    - name: app-a-sidecar
      image: prom/prometheus
      ports:
        - containerPort: 9090
